### ISSUE TITLE
can the script load .blend file

### ISSUE THREAD

**Issue by sakarimov** [30-CherryMagic/first-three.js-page#1]
this is great project, will help so many developer in the future, i have one question about the project, you said that the script will ```put Blender 3D model into webpage byThree.js```, but i can only see .glb there, is it able to also load .blend file?

**Comment by 30-CherryMagic** [comment]
Hi @sakarimov ,
Sorry for the confusion. To be precise, I used Blender to create a 3D model, then exported it as a .glb file, and finally used GLTFLoader to embed the model into a web page. There is no way to load .blender file.
